---
# This file lists all tasks for installing podman, pulling the component images from Docker Hub, and creating data volumes
# Install podman and pull images
- name: check podman install
  package:
    name: podman
    state: latest

- name: install component images
  podman_image:
    name: "{{item}}"
  loop:
    - nginx
    - postgres
    - jboss/keycloak
    - nextcloud
    - matrixdotorg/synapse
    - instrumentisto/coturn



# Create disk volumes (volume names can be cound in group_vars)
- name: podman volumes
  command: podman volume create "{{item}}"
  loop:
    - "{{vol1}}"
    - "{{vol2}}"
    - "{{vol3}}"
...
