---

- name: check podman install
  package:
    name: podman
    state: latest
- name: install nginx
  podman_image:
   name: nginx
- name: install postgres
  podman_image:
   name: postgres
- name: install keycloak
  podman_image:
   name: jboss/keycloak
- name: install nextcloud
  podman_image:
   name: nextcloud
- name: install synapse
  podman_image:
   name: matrixdotorg/synapse
- name: install coturn
  podman_image:
   name: instrumentisto/coturn
# create nextcloud storage volume
# create database volume
...
