---
# Location (Path) of the Matrix homeserver.yaml file from repo
homeserver_repo:

# Location (Path) of the Matrix homeserver.yaml file from live
homeserver_live:

# Location (Path) of the Coturn turnserver.conf file from repo

turnserver_repo:

# Location (Path) of the Coturn turnserver.conf file from live
turnserver_live: 

# Location (Path) of the Keycloak config file from repo

# Location (Path) of the Keycloak config file from live
...
